services:
  mysql:
    image: mysql:8.0
    restart: unless-stopped
    environment: 
      MYSQL_ROOT_PASSWORD: ${handson_root_password}
      MYSQL_DATABASE: ${handson_database}
      MYSQL_USER: ${handson_user}
      MYSQL_PASSWORD: ${handson_password}   
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql    
    networks: 
      - handson_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql 
      PMA_USER: ${handson_user}
      PMA_PASSWORD: ${handson_password}
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - handson_network

volumes:
  mysql_data:

networks:
  handson_network:
